In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv('../Data/MNCAATourneyDetailedResults.csv')

In [14]:
df

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,2019,146,1120,77,1246,71,N,1,26,65,...,21,12,21,11,30,14,14,5,5,19
1111,2019,146,1277,68,1181,67,N,0,30,70,...,21,8,13,13,29,14,17,4,9,9
1112,2019,152,1403,61,1277,51,N,0,22,51,...,24,14,18,8,28,6,11,1,2,15
1113,2019,152,1438,63,1120,62,N,0,25,51,...,31,11,14,9,24,9,5,3,3,12
1114,2019,154,1438,85,1403,77,N,1,27,59,...,30,13,15,9,23,9,8,6,3,18

In [15]:
def possessions(row):
    if 'WFGA' in row:
        possessions = 0.96*(row.WFGA + row.WTO + 0.44*row.WFTA - row.WOR)
    else:
        possessions = 0.96*(row.LFGA + row.LTO + 0.44*row.LFTA - row.LOR)
    return possessions

df['wPoss'] = df[['WFGA', 'WTO', 'WFTA', 'WOR']].apply(possessions, axis=1)
df['lPoss'] = df[['LFGA', 'LTO', 'LFTA', 'LOR']].apply(possessions, axis=1)

In [16]:
# total possession
df['Poss'] = (df['wPoss'] + df['lPoss']) / 2

In [17]:
df

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,wPoss,lPoss,Poss
0,2003,134,1421,92,1411,84,N,1,32,69,...,17,28,16,15,5,0,22,75.3024,75.4944,75.3984
1,2003,136,1112,80,1436,51,N,0,31,66,...,8,26,12,17,10,3,15,74.0736,73.0368,73.5552
2,2003,136,1113,84,1272,71,N,0,31,59,...,20,22,11,12,2,5,18,64.9728,67.4304,66.2016
3,2003,136,1141,79,1166,73,N,0,29,53,...,14,17,20,21,6,6,21,68.1600,71.5008,69.8304
4,2003,136,1143,76,1301,74,N,1,27,64,...,10,26,16,14,5,8,19,66.3552,66.0480,66.2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,2019,146,1120,77,1246,71,N,1,26,65,...,11,30,14,14,5,5,19,69.6576,70.3104,69.9840
1111,2019,146,1277,68,1181,67,N,0,30,70,...,13,29,14,17,4,9,9,65.8944,64.0512,64.9728
1112,2019,152,1403,61,1277,51,N,0,22,51,...,8,28,6,11,1,2,15,58.2912,55.6032,56.9472
1113,2019,152,1438,63,1120,62,N,0,25,51,...,9,24,9,5,3,3,12,56.9088,54.8736,55.8912
1114,2019,154,1438,85,1403,77,N,1,27,59,...,9,23,9,8,6,3,18,66.3552,65.8560,66.1056

In [ ]:
def offReb(row):
    print(row)