In [2]:
import pandas as pd

In [3]:
dRegSeasonResults = pd.read_csv("../Data/MRegularSeasonDetailedResults.csv")
dTourneyResults = pd.read_csv("../Data/MNCAATourneyDetailedResults.csv")

In [4]:
dRegSeasonResults

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92827,2020,128,1389,56,1233,54,N,0,15,60,...,16,18,20,4,27,6,17,8,4,20
92828,2020,128,1393,81,1314,53,N,0,28,61,...,16,11,13,13,29,9,18,0,1,18
92829,2020,128,1402,85,1111,68,H,0,34,57,...,15,25,35,8,17,6,18,7,2,18
92830,2020,128,1412,74,1427,69,N,0,26,53,...,27,7,7,12,22,11,13,4,2,18
92831,2020,128,1450,82,1160,68,N,0,27,55,...,21,22,32,10,24,4,11,4,4,19

In [5]:
# cumulative PIE% of winning and losing teams
# regular season results
dRegSeasonResults['WPIE%'] = dRegSeasonResults.apply(lambda row: ((row.WScore + row.WFGM + row.WFTM - row.WFGA - row.WFTA 
                  + row.WDR + 0.5*row.WOR + row.WAst + row.WStl + 0.5*row.WBlk - row.WPF - row.WTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)
dRegSeasonResults['LPIE%'] = dRegSeasonResults.apply(lambda row: ((row.LScore + row.LFGM + row.LFTM - row.LFGA - row.LFTA 
                  + row.LDR + 0.5*row.LOR + row.LAst + row.LStl + 0.5*row.LBlk - row.LPF - row.LTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)

dRegSeasonResults

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,WPIE%,LPIE%
0,2003,10,1104,68,1328,62,N,0,27,58,...,22,10,22,8,18,9,2,20,0.532847,0.467153
1,2003,10,1272,70,1393,63,N,0,26,62,...,20,20,25,7,12,8,6,16,0.602339,0.397661
2,2003,11,1266,73,1437,61,N,0,24,58,...,23,31,22,9,12,2,5,23,0.736434,0.263566
3,2003,11,1296,56,1457,50,N,0,18,38,...,15,17,20,9,19,4,3,23,0.754717,0.245283
4,2003,11,1400,77,1208,71,N,0,30,61,...,27,21,15,12,10,7,1,14,0.570732,0.429268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92827,2020,128,1389,56,1233,54,N,0,15,60,...,20,4,27,6,17,8,4,20,0.354167,0.645833
92828,2020,128,1393,81,1314,53,N,0,28,61,...,13,13,29,9,18,0,1,18,0.788360,0.211640
92829,2020,128,1402,85,1111,68,H,0,34,57,...,35,8,17,6,18,7,2,18,0.715596,0.284404
92830,2020,128,1412,74,1427,69,N,0,26,53,...,7,12,22,11,13,4,2,18,0.603865,0.396135
92831,2020,128,1450,82,1160,68,N,0,27,55,...,32,10,24,4,11,4,4,19,0.694581,0.305419

In [6]:
dTourneyResults

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,2019,146,1120,77,1246,71,N,1,26,65,...,21,12,21,11,30,14,14,5,5,19
1111,2019,146,1277,68,1181,67,N,0,30,70,...,21,8,13,13,29,14,17,4,9,9
1112,2019,152,1403,61,1277,51,N,0,22,51,...,24,14,18,8,28,6,11,1,2,15
1113,2019,152,1438,63,1120,62,N,0,25,51,...,31,11,14,9,24,9,5,3,3,12
1114,2019,154,1438,85,1403,77,N,1,27,59,...,30,13,15,9,23,9,8,6,3,18

In [7]:
# cumulative PIE% of winning and losing teams
# ncaa tournament results
dTourneyResults['WPIE%'] = dTourneyResults.apply(lambda row: ((row.WScore + row.WFGM + row.WFTM - row.WFGA - row.WFTA 
                  + row.WDR + 0.5*row.WOR + row.WAst + row.WStl + 0.5*row.WBlk - row.WPF - row.WTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)
dTourneyResults['LPIE%'] = dTourneyResults.apply(lambda row: ((row.LScore + row.LFGM + row.LFTM - row.LFGA - row.LFTA 
                  + row.LDR + 0.5*row.LOR + row.LAst + row.LStl + 0.5*row.LBlk - row.LPF - row.LTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)

dTourneyResults

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,WPIE%,LPIE%
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,17,28,16,15,5,0,22,0.594262,0.405738
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,8,26,12,17,10,3,15,0.769231,0.230769
2,2003,136,1113,84,1272,71,N,0,31,59,...,21,20,22,11,12,2,5,18,0.683544,0.316456
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,14,17,20,21,6,6,21,0.585586,0.414414
4,2003,136,1143,76,1301,74,N,1,27,64,...,20,10,26,16,14,5,8,19,0.491667,0.508333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,2019,146,1120,77,1246,71,N,1,26,65,...,21,11,30,14,14,5,5,19,0.511737,0.488263
1111,2019,146,1277,68,1181,67,N,0,30,70,...,13,13,29,14,17,4,9,9,0.496000,0.504000
1112,2019,152,1403,61,1277,51,N,0,22,51,...,18,8,28,6,11,1,2,15,0.605442,0.394558
1113,2019,152,1438,63,1120,62,N,0,25,51,...,14,9,24,9,5,3,3,12,0.545455,0.454545
1114,2019,154,1438,85,1403,77,N,1,27,59,...,15,9,23,9,8,6,3,18,0.577778,0.422222