In [39]:
import pandas as pd

In [40]:
dRegSeasonResults = pd.read_csv("MRegularSeasonDetailedResults.csv")
dTourneyResults = pd.read_csv("MNCAATourneyDetailedResults.csv")

In [41]:
dRegSeasonResults

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92827,2020,128,1389,56,1233,54,N,0,15,60,...,16,18,20,4,27,6,17,8,4,20
92828,2020,128,1393,81,1314,53,N,0,28,61,...,16,11,13,13,29,9,18,0,1,18
92829,2020,128,1402,85,1111,68,H,0,34,57,...,15,25,35,8,17,6,18,7,2,18
92830,2020,128,1412,74,1427,69,N,0,26,53,...,27,7,7,12,22,11,13,4,2,18
92831,2020,128,1450,82,1160,68,N,0,27,55,...,21,22,32,10,24,4,11,4,4,19

In [ ]:
# cumulative PIE% of winning and losing teams
# regular season results
dRegSeasonResults['WPIE%'] = dRegSeasonResults.apply(lambda row: ((row.WScore + row.WFGM + row.WFTM - row.WFGA - row.WFTA 
                  + row.WDR + 0.5*row.WOR + row.WAst + row.WStl + 0.5*row.WBlk - row.WPF - row.WTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)
dRegSeasonResults['LPIE%'] = dRegSeasonResults.apply(lambda row: ((row.LScore + row.LFGM + row.LFTM - row.LFGA - row.LFTA 
                  + row.LDR + 0.5*row.LOR + row.LAst + row.LStl + 0.5*row.LBlk - row.LPF - row.LTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)

dRegSeasonResults

In [ ]:
dTourneyResults

In [34]:
# cumulative PIE% of winning and losing teams
# ncaa tournament results
dTourneyResults['WPIE%'] = dTourneyResults.apply(lambda row: ((row.WScore + row.WFGM + row.WFTM - row.WFGA - row.WFTA 
                  + row.WDR + 0.5*row.WOR + row.WAst + row.WStl + 0.5*row.WBlk - row.WPF - row.WTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)
dTourneyResults['LPIE%'] = dTourneyResults.apply(lambda row: ((row.LScore + row.LFGM + row.LFTM - row.LFGA - row.LFTA 
                  + row.LDR + 0.5*row.LOR + row.LAst + row.LStl + 0.5*row.LBlk - row.LPF - row.LTO) / (row.WScore 
                  + row.LScore + row.WFGM + row.LFGM + row.WFTM + row.LFTM - row.WFGA - row.LFGA - row.WFTA - row.LFTA 
                  + row.WDR + row.LDR + 0.5*row.WOR + 0.5*row.LOR + row.WAst + row.LAst + row.WStl + row.LStl 
                  + 0.5*row.WBlk + 0.5*row.LBlk - row.WPF - row.LPF - row.WTO - row.LTO)), axis=1)

dTourneyResults